-- Add recent official activities and publicly documented member chemistry to every locale.
-- Existing biographies are preserved; these paragraphs are appended to the detailed introductions.
with additions as (
  select key, value
  from jsonb_each_text($member_updates$
  {
    "member.ruka.detail.zh-TW": "近期，RUKA 隨團投入 2026–27《CHOOM》世界巡演；首爾場的個人舞台由成員參與選曲、編曲與舞台方向，更突顯她對節奏與表演結構的掌握。她與 ASA 的音樂默契有正式作品可循：兩位日本成員共同演出〈Woke Up In Tokyo〉，也經常在團體歌曲中接力完成說唱段落。官方幕後內容亦呈現全團會互相監看演出、交換意見與鼓勵，因此這裡描述的是公開可見的創作夥伴關係，而不是替成員設定私下的固定角色。",
    "member.ruka.detail.zh-CN": "近期，RUKA 随团投入 2026–27《CHOOM》世界巡演；首尔场的个人舞台由成员参与选曲、编曲与舞台方向，更突显她对节奏和表演结构的掌握。她与 ASA 的音乐默契有正式作品可循：两位日本成员共同演出《Woke Up In Tokyo》，也经常在团体歌曲中接力完成说唱段落。官方幕后内容也呈现全团会互相观看演出、交换意见并给予鼓励，因此这里描述的是公开可见的创作伙伴关系，而不是替成员设定私下的固定角色。",
    "member.ruka.detail.th": "ช่วงล่าสุด RUKA ร่วมทัวร์โลก CHOOM ปี 2026–27 โดยในคอนเสิร์ตโซล สมาชิกมีส่วนร่วมเลือกเพลง เรียบเรียง และกำหนดทิศทางเวทีเดี่ยวของตนเอง ทำให้เห็นความเข้าใจด้านจังหวะและโครงสร้างการแสดงของเธอชัดขึ้น ความเข้าขากับ ASA มีหลักฐานในผลงานอย่าง Woke Up In Tokyo ซึ่งสมาชิกชาวญี่ปุ่นทั้งสองแสดงร่วมกัน และทั้งคู่มักส่งต่อท่อนแร็ปในเพลงของวง เบื้องหลังทางการยังเผยให้เห็นว่าสมาชิกทุกคนช่วยกันดูผลงาน แลกเปลี่ยนความคิดเห็น และให้กำลังใจ จึงเป็นความสัมพันธ์ด้านการทำงานที่เห็นได้จากสาธารณะ ไม่ใช่การกำหนดบทบาทส่วนตัวให้พวกเธอ",
    "member.ruka.detail.en": "More recently, RUKA joined the 2026–27 CHOOM world tour. For the Seoul concerts, each member took part in choosing, arranging, and directing her solo stage, further highlighting RUKA's command of rhythm and performance structure. Her musical connection with ASA is documented in official work: the two Japanese members perform Woke Up In Tokyo together and frequently hand rap passages from one to the other in group songs. Official behind-the-scenes content also shows all members monitoring performances, exchanging feedback, and offering encouragement, so this describes a visible creative partnership rather than assigning them private roles.",
    "member.ruka.detail.ko": "최근 RUKA는 2026–27 CHOOM 월드 투어에 참여하고 있습니다. 서울 공연의 솔로 무대에서는 멤버들이 직접 선곡, 편곡과 무대 연출에 참여해 RUKA의 리듬 감각과 공연 구성 능력이 더욱 선명하게 드러났습니다. ASA와의 음악적 호흡은 공식 작업에서도 확인됩니다. 두 일본인 멤버는 Woke Up In Tokyo를 함께 선보였고 단체곡에서도 랩 파트를 자연스럽게 주고받습니다. 공식 비하인드에서는 모든 멤버가 서로의 무대를 모니터링하고 의견과 응원을 나누는 모습도 공개되었으므로, 이는 사적인 역할을 단정한 표현이 아니라 공개적으로 확인되는 창작 파트너십을 설명한 것입니다.",
    "member.ruka.detail.ja": "近年は2026–27年の『CHOOM』ワールドツアーに参加。ソウル公演のソロステージでは、各メンバーが選曲、アレンジ、演出に関わり、RUKAのリズム感とステージ構成への理解がより鮮明に表れました。ASAとの音楽的な関係は公式作品にも残されています。日本出身の2人はWoke Up In Tokyoを共に披露し、グループ曲でもラップを受け渡します。公式の舞台裏では全員が互いのパフォーマンスを確認し、意見と励ましを交わす姿も公開されているため、ここでは私生活上の役割ではなく、公に確認できる創作上のパートナーシップを紹介しています。",

    "member.pharita.detail.zh-TW": "2026 年《CHOOM》活動讓 PHARITA 展現更寬廣的概念消化力：她先以明亮自在的〈I LIKE IT〉呈現夏日氣息，之後又與 ASA 率先公開〈MOON〉的神祕視覺。她與 CHIQUITA 同為泰國成員，官方曼谷花絮記錄了兩人首次在家人與朋友面前演出時既緊張又期待，全團也為當地交流練習泰語，演出後彼此以笑容安慰。這段公開經歷顯示 PHARITA 不只連結泰國觀眾，也和成員一起承擔跨語言、跨文化活動。",
    "member.pharita.detail.zh-CN": "2026 年《CHOOM》活动让 PHARITA 展现更广的概念驾驭力：她先在明亮自在的《I LIKE IT》中呈现夏日气息，之后又与 ASA 率先公开《MOON》的神秘视觉。她和 CHIQUITA 同为泰国成员，官方曼谷花絮记录了两人首次在家人和朋友面前演出时既紧张又期待，全团也为当地交流练习泰语，演出后彼此以笑容安慰。这段公开经历显示 PHARITA 不只连接泰国观众，也和成员一起承担跨语言、跨文化活动。",
    "member.pharita.detail.th": "กิจกรรม CHOOM ในปี 2026 แสดงให้เห็นว่า PHARITA ถ่ายทอดคอนเซปต์ได้กว้างขึ้น ตั้งแต่บรรยากาศฤดูร้อนที่สดใสและเป็นอิสระของ I LIKE IT ไปจนถึงภาพลึกลับของ MOON ที่เธอเปิดตัวเป็นคู่แรกกับ ASA เธอและ CHIQUITA เป็นสมาชิกชาวไทย โดยเบื้องหลังทางการที่กรุงเทพฯ บันทึกความตื่นเต้นและประหม่าของทั้งคู่เมื่อต้องแสดงต่อหน้าครอบครัวและเพื่อนเป็นครั้งแรก สมาชิกทั้งวงยังฝึกภาษาไทยเพื่อสื่อสารกับแฟน ๆ และปลอบใจกันด้วยรอยยิ้มหลังเวที ประสบการณ์นี้แสดงให้เห็นว่า PHARITA ไม่เพียงเชื่อมโยงกับผู้ชมชาวไทย แต่ยังทำงานร่วมกับสมาชิกในกิจกรรมข้ามภาษาและวัฒนธรรมด้วย",
    "member.pharita.detail.en": "The 2026 CHOOM era has shown PHARITA's widening conceptual range: she moved from the bright, free summer mood of I LIKE IT to the mysterious MOON visuals, where she and ASA formed the first revealed pair. PHARITA and CHIQUITA are BABYMONSTER's Thai members; official Bangkok footage documented their nervous excitement before performing in front of family and friends for the first time. The entire group studied Thai for local communication and comforted one another with warm smiles after the show. That public experience shows PHARITA connecting with Thai audiences while sharing the demands of multilingual, cross-cultural activity with her members.",
    "member.pharita.detail.ko": "2026년 CHOOM 활동은 PHARITA의 넓어진 콘셉트 소화력을 보여 줍니다. 밝고 자유로운 여름 분위기의 I LIKE IT에 이어 ASA와 첫 번째 페어로 공개된 MOON 비주얼에서는 신비로운 분위기를 표현했습니다. PHARITA와 CHIQUITA는 팀의 태국인 멤버로, 방콕 공식 비하인드에는 두 사람이 처음으로 가족과 친구들 앞에서 공연하며 긴장하고 설레는 모습이 담겼습니다. 멤버 전원이 현지 소통을 위해 태국어를 연습하고 공연 뒤 따뜻한 미소로 서로를 위로하기도 했습니다. 이는 PHARITA가 태국 관객과 연결되는 동시에 멤버들과 다언어·다문화 활동을 함께 감당하는 모습을 보여 줍니다.",
    "member.pharita.detail.ja": "2026年の『CHOOM』活動では、PHARITAのコンセプト表現の幅がさらに広がりました。明るく自由な夏の空気を持つI LIKE ITから、ASAと最初のペアとして公開されたMOONの神秘的なビジュアルまで、異なるムードを見せています。PHARITAとCHIQUITAはタイ出身メンバーで、公式のバンコク舞台裏映像には、家族や友人の前で初めて公演する2人の緊張と喜びが記録されています。全員が現地での交流のためにタイ語を練習し、公演後には笑顔で励まし合いました。PHARITAがタイの観客とつながりながら、多言語・多文化の活動をメンバーと共に担う姿が伝わります。",

    "member.asa.detail.zh-TW": "ASA 的團內合作有多條公開脈絡。她與 RUKA 以〈Woke Up In Tokyo〉建立鮮明的日本成員說唱單元；2026 年〈MOON〉宣傳中，她又與 PHARITA 以第一組視覺搭檔呈現夢幻暗色概念。〈WE GO UP〉幕後還拍到 RORA 幫她整理妝容並拍照，呈現工作現場自然互助的一面。從說唱創作、概念拍攝到與不同成員的搭配，ASA 的角色更像能依作品需求快速建立化學反應的創作者與表演者。",
    "member.asa.detail.zh-CN": "ASA 的团内合作有多条公开脉络。她与 RUKA 通过《Woke Up In Tokyo》建立鲜明的日本成员说唱组合；2026 年《MOON》宣传中，她又与 PHARITA 以第一组视觉搭档呈现梦幻暗色概念。《WE GO UP》幕后还拍到 RORA 帮她整理妆容并拍照，呈现工作现场自然互助的一面。从说唱创作、概念拍摄到与不同成员的搭配，ASA 更像是一位能按照作品需求迅速建立化学反应的创作者和表演者。",
    "member.asa.detail.th": "ความร่วมมือของ ASA กับสมาชิกมีให้เห็นอย่างชัดเจนหลายด้าน เธอกับ RUKA สร้างยูนิตแร็ปของสมาชิกชาวญี่ปุ่นผ่าน Woke Up In Tokyo ขณะที่การโปรโมต MOON ปี 2026 เธอจับคู่กับ PHARITA เป็นคู่ภาพแรกในคอนเซปต์มืดและชวนฝัน เบื้องหลัง WE GO UP ยังเผยให้เห็น RORA ช่วยแต่งหน้าและถ่ายรูปให้เธอ ซึ่งสะท้อนการช่วยเหลือกันอย่างเป็นธรรมชาติในที่ทำงาน ตั้งแต่การสร้างสรรค์แร็ป การถ่ายคอนเซปต์ ไปจนถึงการจับคู่กับสมาชิกหลายคน ASA จึงเป็นทั้งผู้สร้างสรรค์และนักแสดงที่ปรับตัวเพื่อสร้างเคมีตามความต้องการของผลงานได้รวดเร็ว",
    "member.asa.detail.en": "ASA has several well-documented creative connections within the group. Woke Up In Tokyo gives her and RUKA a distinct Japanese-member rap unit, while the 2026 MOON campaign paired her with PHARITA as the first visual duo for its dark, dreamlike concept. WE GO UP behind-the-scenes footage also showed RORA helping with ASA's makeup and taking photos for her, capturing natural teamwork on set. Across rap creation, concept shoots, and pairings with different members, ASA comes across as a creator and performer who quickly builds chemistry around what each project requires.",
    "member.asa.detail.ko": "ASA는 팀 안에서 여러 멤버와 뚜렷한 창작 호흡을 보여 왔습니다. RUKA와는 Woke Up In Tokyo를 통해 일본인 멤버 랩 유닛의 색깔을 만들었고, 2026년 MOON 프로모션에서는 PHARITA와 첫 비주얼 페어로 등장해 어둡고 몽환적인 콘셉트를 표현했습니다. WE GO UP 비하인드에서는 RORA가 ASA의 메이크업을 도와주고 사진을 찍어 주는 자연스러운 현장 협업도 공개되었습니다. 랩 창작과 콘셉트 촬영, 다양한 멤버와의 조합을 오가며 ASA는 작품이 요구하는 케미스트리를 빠르게 만드는 창작자이자 퍼포머의 모습을 보여 줍니다.",
    "member.asa.detail.ja": "ASAには、グループ内で公に確認できる複数の創作的なつながりがあります。RUKAとはWoke Up In Tokyoで日本出身メンバーによるラップユニットの色を築き、2026年のMOONプロモーションではPHARITAと最初のビジュアルペアとして、ダークで幻想的なコンセプトを表現しました。WE GO UPの舞台裏では、RORAがASAのメイクを手伝い、写真を撮る自然な協力場面も公開されています。ラップ制作、コンセプト撮影、さまざまなメンバーとの組み合わせを通して、ASAは作品に必要な相乗効果を素早く作るクリエイター兼パフォーマーとして映ります。",

    "member.ahyeon.detail.zh-TW": "近期的 AHYEON 持續在不同組合中展現全能面貌。2026 年〈MOON〉視覺中，她與 RORA 同組，以濃烈造型和克制表情共同完成電影感的暗色氣氛；在早期〈SHEESH〉製作紀錄裡，她則與 ASA、RUKA 串連第二段說唱，呈現三種聲線的對比。團體出道訪談曾公開提到，成員在她暫停活動期間給予鼓勵，而大家也認為七人一起出道是自然且完整的狀態。這些公開資料能說明她與成員間的關係核心是舞台互補與彼此支持。",
    "member.ahyeon.detail.zh-CN": "近期的 AHYEON 持续在不同组合中展现全能面貌。2026 年《MOON》视觉中，她与 RORA 同组，以浓烈造型和克制表情共同完成电影感的暗色氛围；在早期《SHEESH》制作记录里，她则与 ASA、RUKA 串联第二段说唱，呈现三种声线的对比。团体出道访问曾公开提到，成员在她暂停活动期间给予鼓励，大家也认为七人一起出道是自然且完整的状态。这些公开资料说明她与成员之间的关系核心是舞台互补与彼此支持。",
    "member.ahyeon.detail.th": "ช่วงล่าสุด AHYEON ยังคงแสดงความสามารถรอบด้านผ่านการจับคู่ที่หลากหลาย ในภาพ MOON ปี 2026 เธอจับคู่กับ RORA ถ่ายทอดบรรยากาศมืดแบบภาพยนตร์ด้วยลุคเข้มและสีหน้าที่ควบคุมอย่างดี ส่วนสารคดีการผลิต SHEESH ก่อนหน้านั้นแสดงให้เห็นการส่งต่อท่อนแร็ประหว่างเธอ ASA และ RUKA ซึ่งทำให้สีเสียงทั้งสามตัดกันอย่างน่าสนใจ บทสัมภาษณ์ช่วงเดบิวต์ยังระบุว่าสมาชิกให้กำลังใจเธอระหว่างพักกิจกรรม และทุกคนมองว่าการเดบิวต์พร้อมกันเจ็ดคนเป็นสิ่งที่เป็นธรรมชาติและสมบูรณ์ ข้อมูลสาธารณะเหล่านี้สะท้อนว่าความสัมพันธ์ของเธอกับสมาชิกตั้งอยู่บนการเสริมกันบนเวทีและการสนับสนุนซึ่งกันและกัน",
    "member.ahyeon.detail.en": "AHYEON continues to show her all-round range through different member combinations. In the 2026 MOON visuals, she and RORA built a cinematic dark mood through intense styling and restrained expressions. In the earlier SHEESH production documentary, AHYEON, ASA, and RUKA linked the second-verse rap, contrasting three distinct voices. The group's debut interview also recorded that members encouraged AHYEON during her break and regarded debuting together as seven as the natural, complete outcome. These public accounts frame her relationships with the members around complementary stage skills and mutual support.",
    "member.ahyeon.detail.ko": "최근 AHYEON은 여러 멤버 조합에서 올라운더의 면모를 이어 가고 있습니다. 2026년 MOON 비주얼에서는 RORA와 한 페어로 등장해 강렬한 스타일링과 절제된 표정으로 영화 같은 어두운 분위기를 완성했습니다. 앞선 SHEESH 제작 다큐멘터리에서는 ASA, RUKA와 두 번째 벌스의 랩을 연결하며 서로 다른 세 음색의 대비를 만들었습니다. 데뷔 인터뷰에는 활동을 쉬는 동안 멤버들이 AHYEON을 격려했고, 모두가 일곱 명의 데뷔를 자연스럽고 완전한 모습으로 여겼다는 이야기도 담겼습니다. 이러한 공개 기록은 멤버들과의 관계가 무대 위 상호 보완과 서로에 대한 지지를 중심으로 형성되어 있음을 보여 줍니다.",
    "member.ahyeon.detail.ja": "近年のAHYEONは、さまざまなメンバーとの組み合わせでオールラウンドな力を見せています。2026年のMOONビジュアルではRORAとペアになり、強いスタイリングと抑えた表情で映画的なダークムードを完成させました。以前のSHEESH制作ドキュメンタリーでは、ASA、RUKAと第2ヴァースのラップをつなぎ、3人の異なる声を対比させています。デビュー時のインタビューでは、活動休止中にメンバーがAHYEONを励まし、7人でのデビューを自然で完全な形だと考えていたことも語られました。公に確認できるこれらの記録から、メンバーとの関係はステージ上の相互補完と支え合いを軸にしていることが分かります。",

    "member.rami.detail.zh-TW": "RAMI 與成員長期共同成長的痕跡也留在官方社群。ASA 曾在生日貼文回顧兩人從年幼練習生時期一路成長約六年，並提到一起在電腦前嘗試音樂創作；這讓她們的關係不只停留在同團成員，也包含長期練習與創作記憶。YG 於 2025 年公告 RAMI 因健康因素暫停部分活動並以休養為優先；在官方發布進一步消息前，本站不推測病況或復出時間，只保留她作為 BABYMONSTER 成員及重要聲線的介紹。",
    "member.rami.detail.zh-CN": "RAMI 与成员长期共同成长的痕迹也留在官方社区。ASA 曾在生日帖子中回顾两人从年幼练习生时期一路成长约六年，并提到一起在电脑前尝试音乐创作；这让她们的关系不只停留在同团成员，也包含长期训练与创作记忆。YG 于 2025 年公告 RAMI 因健康因素暂停部分活动并以休养为优先；在官方发布进一步消息前，本站不推测病情或复出时间，只保留她作为 BABYMONSTER 成员及重要声线的介绍。",
    "member.rami.detail.th": "ร่องรอยของการเติบโตไปพร้อมกับสมาชิกมาอย่างยาวนานของ RAMI ปรากฏอยู่ในชุมชนทางการ ASA เคยเขียนอวยพรวันเกิดและย้อนถึงเวลาประมาณหกปีที่ทั้งคู่เติบโตมาตั้งแต่เป็นเด็กฝึก รวมถึงความทรงจำที่เคยนั่งทดลองทำเพลงหน้าคอมพิวเตอร์ด้วยกัน ความสัมพันธ์จึงมีทั้งประสบการณ์การฝึกและความทรงจำด้านการสร้างสรรค์ ไม่ได้จำกัดเพียงการเป็นสมาชิกวงเดียวกัน ในปี 2025 YG ประกาศว่า RAMI จะพักบางกิจกรรมด้วยเหตุผลด้านสุขภาพและให้ความสำคัญกับการพักฟื้น เว็บไซต์นี้จะไม่คาดเดาอาการหรือกำหนดกลับมาจนกว่าจะมีประกาศทางการเพิ่มเติม และยังคงแนะนำเธอในฐานะสมาชิกและหนึ่งในเสียงสำคัญของ BABYMONSTER",
    "member.rami.detail.en": "RAMI's long history of growing alongside the members is also recorded on the official community. In a birthday post, ASA looked back on roughly six years together since their early trainee days and remembered the two experimenting with music at a computer. Their connection therefore includes years of training and creative memories, not only membership in the same group. In 2025, YG announced that RAMI would pause activities for health reasons and prioritize rest. Until a further official update is published, this site does not speculate about her condition or return date and continues to present her as a BABYMONSTER member and an important voice in the group.",
    "member.rami.detail.ko": "RAMI가 멤버들과 오랫동안 함께 성장해 온 흔적은 공식 커뮤니티에도 남아 있습니다. ASA는 생일 게시물에서 어린 연습생 시절부터 약 6년을 함께 자라 온 시간을 돌아보며, 두 사람이 컴퓨터 앞에서 재미로 음악 작업을 했던 기억을 전했습니다. 두 사람의 연결에는 같은 팀이라는 사실을 넘어 오랜 훈련과 창작의 기억이 담겨 있습니다. YG는 2025년 RAMI가 건강상의 이유로 일부 활동을 중단하고 휴식을 우선한다고 공지했습니다. 추가 공식 발표가 나오기 전까지 이 사이트는 상태나 복귀 시점을 추측하지 않으며, RAMI를 BABYMONSTER의 멤버이자 팀의 중요한 목소리로 계속 소개합니다.",
    "member.rami.detail.ja": "RAMIがメンバーと長く成長してきた記録は、公式コミュニティにも残っています。ASAは誕生日の投稿で、幼い練習生時代から約6年間を共に過ごしたことを振り返り、2人でパソコンに向かって音楽制作を試した思い出にも触れました。その関係には、同じグループというだけでなく、長い練習と創作の記憶があります。YGは2025年、RAMIが健康上の理由で一部活動を休止し、休養を優先すると発表しました。今後の公式発表までは状態や復帰時期を推測せず、BABYMONSTERのメンバーであり、グループの大切な歌声として紹介を続けます。",

    "member.rora.detail.zh-TW": "2026 年〈MOON〉視覺中，RORA 與 AHYEON 共同詮釋暗色電影感；她以冷靜視線和克制表情，與 AHYEON 的強烈形象形成互補。她和 ASA 的互動則在〈WE GO UP〉幕後留下輕鬆一面：RORA 幫 ASA 整理妝容並替她拍照。官方〈PSYCHO〉幕後也記錄全團在個人拍攝時彼此監看、用鼓勵降低緊張。這些片段讓 RORA 的沉穩不只存在於歌聲，也體現在她觀察現場、支援隊友的方式。",
    "member.rora.detail.zh-CN": "2026 年《MOON》视觉中，RORA 与 AHYEON 共同诠释暗色电影感；她以冷静眼神和克制表情，与 AHYEON 的强烈形象形成互补。她和 ASA 的互动则在《WE GO UP》幕后留下轻松一面：RORA 帮 ASA 整理妆容并为她拍照。官方《PSYCHO》幕后也记录全团在个人拍摄时互相观看、用鼓励降低紧张。这些片段说明 RORA 的沉稳不只存在于歌声，也体现在她观察现场和支持队友的方式。",
    "member.rora.detail.th": "ในภาพ MOON ปี 2026 RORA ถ่ายทอดบรรยากาศมืดแบบภาพยนตร์ร่วมกับ AHYEON สายตาสงบและสีหน้าที่ควบคุมของเธอช่วยเสริมภาพลักษณ์อันเข้มข้นของ AHYEON อีกด้านหนึ่ง เบื้องหลัง WE GO UP เผยช่วงเวลาสบาย ๆ ระหว่าง RORA กับ ASA เมื่อเธอช่วยแต่งหน้าและถ่ายรูปให้ ASA ส่วนเบื้องหลัง PSYCHO ทางการยังบันทึกว่าสมาชิกทุกคนคอยดูการถ่ายเดี่ยวของกันและกันและใช้คำให้กำลังใจเพื่อลดความกังวล ภาพเหล่านี้แสดงว่าความสุขุมของ RORA ไม่ได้อยู่เพียงในเสียงร้อง แต่ยังอยู่ในวิธีสังเกตสถานการณ์และสนับสนุนเพื่อนร่วมวง",
    "member.rora.detail.en": "In the 2026 MOON visuals, RORA and AHYEON interpreted a cinematic dark concept together; RORA's calm gaze and restrained expression complemented AHYEON's more intense transformation. Her connection with ASA appeared in a lighter WE GO UP behind-the-scenes moment, where RORA helped with ASA's makeup and took photos for her. Official PSYCHO footage also documented the whole group monitoring one another's solo takes and using encouragement to ease tension. These moments show that RORA's composure is present not only in her voice, but also in how she observes a set and supports her teammates.",
    "member.rora.detail.ko": "2026년 MOON 비주얼에서 RORA는 AHYEON과 함께 영화 같은 어두운 콘셉트를 해석했습니다. 차분한 시선과 절제된 표정은 AHYEON의 강렬한 변신과 서로를 보완했습니다. ASA와의 관계는 WE GO UP 비하인드의 편안한 장면에서도 드러납니다. RORA는 ASA의 메이크업을 도와주고 사진을 찍어 주었습니다. 공식 PSYCHO 비하인드에는 멤버 전원이 서로의 개인 촬영을 모니터링하고 격려로 긴장을 덜어 주는 모습도 기록되었습니다. 이런 순간들은 RORA의 안정감이 목소리뿐 아니라 현장을 살피고 동료를 돕는 방식에도 나타난다는 것을 보여 줍니다.",
    "member.rora.detail.ja": "2026年のMOONビジュアルでは、RORAとAHYEONが映画的なダークコンセプトを共に表現しました。RORAの落ち着いた視線と抑制された表情が、AHYEONの強いイメージチェンジを補完しています。ASAとの関係は、WE GO UPの舞台裏にある柔らかな場面にも表れました。RORAはASAのメイクを手伝い、写真を撮っています。公式のPSYCHO舞台裏では、全員が互いのソロ撮影を確認し、励ましの言葉で緊張を和らげる姿も記録されました。RORAの安定感は歌声だけでなく、現場を見て仲間を支える方法にも現れています。",

    "member.chiquita.detail.zh-TW": "近期，CHIQUITA 在〈WE GO UP〉動作概念中以「Fighter」角色完成有力量的格鬥場面，到了 2026《CHOOM》時期又在更明亮與更神祕的作品之間切換，顯示表情和動作控制持續成長。她與 PHARITA 共享泰國背景，官方曼谷花絮記錄兩人首次在家人與朋友面前演出的緊張與感動；當晚成員們也彼此安慰。作為最年少成員，她和姐姐們的公開互動更適合被理解為共同練習、互相照顧並一起適應全球行程，而不是單一的「可愛忙內」形象。",
    "member.chiquita.detail.zh-CN": "近期，CHIQUITA 在《WE GO UP》动作概念中以“Fighter”角色完成有力量的格斗场面，到了 2026《CHOOM》时期又在更明亮和更神秘的作品之间切换，显示表情与动作控制持续成长。她和 PHARITA 共享泰国背景，官方曼谷幕后记录了两人首次在家人和朋友面前演出的紧张与感动；当晚成员们也彼此安慰。作为最年少成员，她与姐姐们的公开互动更适合被理解为共同训练、互相照顾并一起适应全球行程，而不是单一的“可爱忙内”形象。",
    "member.chiquita.detail.th": "ช่วงล่าสุด CHIQUITA รับบท Fighter ในคอนเซปต์แอ็กชันของ WE GO UP และแสดงฉากต่อสู้อันทรงพลัง ก่อนจะสลับระหว่างผลงานที่สดใสกับบรรยากาศลึกลับในยุค CHOOM ปี 2026 แสดงให้เห็นว่าการควบคุมสีหน้าและการเคลื่อนไหวของเธอพัฒนาต่อเนื่อง เธอกับ PHARITA มีพื้นเพจากประเทศไทยร่วมกัน และเบื้องหลังทางการที่กรุงเทพฯ บันทึกความประหม่าและความซาบซึ้งของทั้งคู่เมื่อแสดงต่อหน้าครอบครัวและเพื่อนเป็นครั้งแรก สมาชิกยังปลอบใจกันในคืนนั้น ในฐานะน้องเล็ก ความสัมพันธ์ที่เปิดเผยต่อสาธารณะของเธอกับพี่ ๆ จึงควรถูกมองว่าเป็นการฝึกฝน ดูแลกัน และปรับตัวกับตารางงานทั่วโลกร่วมกัน มากกว่าจะจำกัดเธอไว้เพียงภาพน้องเล็กที่น่ารัก",
    "member.chiquita.detail.en": "More recently, CHIQUITA took the Fighter role in WE GO UP's action concept and delivered powerful combat scenes. During the 2026 CHOOM era she has moved between brighter and more mysterious material, showing continued growth in facial and movement control. She shares a Thai background with PHARITA, and official Bangkok footage recorded both members' nerves and emotion before performing for family and friends for the first time; the members comforted one another that evening. As the youngest member, her public interactions with the others are best understood as training, caring for one another, and adapting to global schedules together—not simply a one-note cute-maknae image.",
    "member.chiquita.detail.ko": "최근 CHIQUITA는 WE GO UP의 액션 콘셉트에서 Fighter 역할로 힘 있는 격투 장면을 소화했습니다. 2026년 CHOOM 시기에는 밝은 작품과 신비로운 분위기의 작품을 오가며 표정과 동작 제어가 계속 성장하고 있음을 보여 줍니다. PHARITA와 같은 태국 출신으로, 공식 방콕 비하인드에는 두 사람이 처음 가족과 친구들 앞에서 공연하며 느낀 긴장과 감동이 기록되었습니다. 그날 멤버들은 서로를 따뜻하게 위로하기도 했습니다. 막내인 CHIQUITA와 언니들의 공개 관계는 단순히 귀여운 막내 이미지로 한정하기보다 함께 연습하고 서로 돌보며 글로벌 일정을 적응해 가는 과정으로 보는 것이 알맞습니다.",
    "member.chiquita.detail.ja": "近年、CHIQUITAはWE GO UPのアクションコンセプトでFighter役を担い、力強い格闘シーンを披露しました。2026年の『CHOOM』期には、明るい作品と神秘的な作品を行き来し、表情と動きのコントロールが成長し続けていることを示しています。PHARITAと同じタイ出身で、公式のバンコク舞台裏映像には、家族や友人の前で初めて公演する2人の緊張と感動が記録され、メンバー同士が慰め合う姿もありました。最年少のCHIQUITAと年上メンバーの公の関係は、単なる可愛い末っ子像ではなく、共に練習し、支え合い、世界規模の日程に適応する過程として見るのが適切です。"
  }
  $member_updates$::jsonb)
), merged as (
  select jsonb_object_agg(
    additions.key,
    concat_ws(E'\n\n', nullif(site_content.value->>additions.key, ''), additions.value)
  ) as value
  from public.site_content
  cross join additions
  where site_content.key = 'uiText'
)
update public.site_content
set value = site_content.value || merged.value
from merged
where site_content.key = 'uiText';
